liongram/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from demos.views import lotto, lotto_result
from posts.views import index, url_view, url_parameter_view, function_view, class_view, function_list_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lotto/', lotto, name="lotto"),
    path('lotto/result/', lotto_result, name='lotto_result'),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('fbv/list', function_list_view),
    path('cbv/', class_view.as_view()),

    path('', index, name="index"),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('__debug__', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

liongram/posts/urls.py
from django.urls import path
from .views import post_create_form_view, post_delete_view, post_detail_view, post_list_view, post_update_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name="post-list"),
    path('create/', post_create_form_view, name='post-create'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('edit/<int:id>/', post_update_view, name='post-update'),
    path('delete/<int:id>/', post_delete_view, name="post-delete"),
]

liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()

class Post(models.Model):
    image = models.ImageField(verbose_name="이미지", null = True, blank=True)
    content = models.TextField("내용")
    created_at = models.DateTimeField("작성일", auto_now_add=True)
    view_count = models.IntegerField("조회수", default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

class Comment(models.Model):
    content = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(verbose_name="작성일", auto_now_add=True)
    post = models.ForeignKey(to="Post", on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User,on_delete=models.CASCADE)

liongram/posts/forms.py
from django import forms
from .models import Post

# class PostBaseForm(forms.Form):
#     image = forms.ImageField()
#     content = forms.CharField(widget = forms.Textarea)

class PostBaseForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

class PostCreateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields = ['image', 'content']

liongram/posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import Http404, HttpResponse
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required

from .models import Post
from .forms import PostBaseForm, PostCreateForm

def index(request):
    post_list = Post.objects.all().order_by('-created_at')
    context = {
        'post_list':post_list
    }
    return render(request, 'index.html', context)

def post_list_view(request):
    post_list = Post.objects.filter(writer = request.user)
    context = {
        'post_list':post_list
    }
    return render(request, 'posts/post_list.html', context)

@login_required
def post_delete_view(request, id):
    post = get_object_or_404(Post, id=id, writer=request.user)
    # if request.user != post.writer:
    #     raise Http404('잘못된 접근입니다.')
    
    if request.method =='GET':
        context = {
            'post':post
        }
        return render(request, 'posts/post_confirm_delete.html', context)
    else:
        post.delete()
        return redirect('index')


def post_detail_view(request, id):
    if request.method=='GET':
        if request.user.is_authenticated:
            try:
                post = Post.objects.get(id=id)
            except Post.DoesNotExist:
                return redirect('index')
            context = {
                'post':post
            }
            return render(request, 'posts/post_detail.html', context)
        else:
            return redirect('accounts:login')

@login_required
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html')
    else:
        image = request.FILES.get('image')
        content = request.POST.get('content')
        Post.objects.create(
            image = image,
            content = content,
            writer = request.user
        )
        return redirect('index')
    
def post_create_form_view(request):
    if request.method == 'GET':
        form = PostCreateForm()
        context = {'form': form}
        return render(request, 'posts/post_form2.html', context)
    else:
        form = PostBaseForm(request.POST, request.FILES)

        if form.is_valid():
            Post.objects.create(
                image=form.cleaned_data['image'],
                content = form.cleaned_data['content'],
                writer=request.user,
            )
        else:
            return redirect('posts:post-create')
        return redirect('index')

@login_required
def post_update_view(request, id):
    #post = Post.objects.get(id = id)
    post = get_object_or_404(Post, id=id, writer = request.user)

    if request.method == 'GET':
        context = {
            'post' : post
        }
        return render(request, 'posts/post_form.html', context)
    elif request.method == 'POST':
        new_image = request.FILES.get('image')
        content = request.POST.get('content')
        
        if new_image:
            post.image.delete()
            post.image = new_image
            
        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id)

# Create your views here.
def url_view(request):
    print('url_view()')
    data = {'code': '001', 'msg': 'OK'}
    return HttpResponse('<h1>url_view</h1>')

def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)

def function_view(request):
    print(f'request.method:{request.method}')

    if request.method == 'GET':
        print(f'request.GET:{request.GET}')
    elif request.method == 'POST':
        print(f'request.POST:{request.POST}')
    return render(request, 'view.html')

class class_view(ListView):
    model = Post
    ordering = ['-id']
    template_name = 'cbv_view.html'


def function_list_view(request):
    object_list = Post.objects.all().order_by('-id')
    return render(request, 'cbv_view.html', {'object_list' : object_list})

liongram/templates/mixin/posts/post_card.html
{% load static %}
<div class="card">
    <div class="card__header">
        <img src="http://via.placeholder.com/32x32" alt="프로필이미지">
        <a href="#">
            <span class="card__user-name">{{post.writer}}</span>
        </a>
    </div>
    {% if request.user == post.writer %}
    <a href="{% url 'posts:post-update' post.id %}">수정하기</a>
    <a href="{% url 'posts:post-delete' post.id %}">삭제하기</a>
    {% endif %}
    <div class="card__body">
        <div>
            {% if post.image %}
            <img class="card__image" src="{{post.image.url}}" alt="">
            {% else %}
            <img class="card__image" src="http://via.placeholder.com/600x600" alt="">
            {% endif %}
        </div>
    </div>
    <div class="card__btn-group">
        <div>
            <img class="card__btn" src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요">
            <img class="card__btn" src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="댓글">
            <img class="card__btn" src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="공유하기">
        </div>
        <div>
            <img class="card__btn" src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="북마크">
        </div>
    </div>
    <div class="card_content">
        <span class="card__like-num">좋아요 00개</span>
        <div class="card__main-text">
            <p><span class="card__user-name">{{post.writer}}</span>
                {% if not detail %}
                {{ post.content|truncatechars:35 }}
                {% else %}
                {{ post.content }}
                {% endif %}
            </p>
            {% if not detail %}
            <a href="{% url 'posts:post-detail' post.id%}">더보기</a>
            {% endif %}
        </div>
        <div>
            <p>댓글 {{post.comment_set.all.count}}개 {% if not detail %}
                <a href="{% url 'posts:post-detail' post.id%}">모두 보기</a>
                {% endif %}</p>
            <ul class="card__comment-group">
                {% if not detail %}
                    {% for comment in post.comment_set.all|slice:":2" %}
                    <li>
                        <p><span class="card__user-name">{{comment.writer}}</span>{{comment.content}}</p>
                    </li>
                    {% endfor %}
                {% else %}
                    {% for comment in post.comment_set.all %}
                    <li>
                        <p><span class="card__user-name">{{comment.writer}}</span>{{comment.content}}</p>
                    </li>
                    {% endfor %}
                {% endif %}
            </ul>
            <p class="card__created-at">{{post.created_at|date:"Y년 m월 d일"}}</p>
        </div>
    </div>
</div>