liongram/accounts/urls.py
from django.urls import path

from .views import signup_view, login_view, logout_view

app_name = 'accouts'

urlpatterns = [
    path('signup/', signup_view, name = 'signup'),
    path('login/', login_view, name ='login'),
    path('logout/', logout_view, name= "logout")
]

liongram/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from demos.views import lotto, lotto_result
from posts.views import index, url_view, url_parameter_view, function_view, class_view, function_list_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lotto/', lotto, name="lotto"),
    path('lotto/result/', lotto_result, name='lotto_result'),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('fbv/list', function_list_view),
    path('cbv/', class_view.as_view()),

    path('', index, name="index"),
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('__debug__', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

liongram/posts/urls.py
from django.urls import path
from .views import post_create_form_view, post_delete_view, post_detail_view, post_list_view, post_update_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name="post-list"),
    path('create/', post_create_form_view, name='post-create'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('edit/<int:id>/', post_update_view, name='post-update'),
    path('delete/<int:id>/', post_delete_view, name="post-delete"),
]

liongram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | 라이언그램</title>
</head>

<body class="container">
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <div>
        <nav>
            <ul class="bottom-menu-group">
                <a href="{% url 'index' %}">
                    <li><img src="{% static 'icons/home_outlined_black_36dp.svg' %}" alt="홈"></li>
                </a>
                <li><img src="{% static 'icons/search_outlined_black_36dp.svg' %}" alt="검색"></li>
                <a href="{% url 'posts:post-create' %}">
                    <li><img src="{% static 'icons/add_box_outlined_black_36dp.svg' %}" alt="글쓰기"></li>
                </a>
                <li><img src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요"></li>
                <li><img src="{% static 'icons/account_circle_outlined_black_36dp.svg' %}" alt="프로필"></li>
            </ul>
        </nav>
        {% if request.user.is_authenticated %}
        <div>
            {{user.username}}님 환영합니다.
        </div>
        <a href="{% url 'accounts:logout' %}">로그아웃</a>
        {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
        {% endif %}
    </div>
</body>

</html>

liongram/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}홈{% endblock %}
{%block content %}
<main>
    <div class="card-list">
        {% for post in post_list %}
        {% include 'mixin/posts/post_card.html' with detail=False %}
        {%endfor %}
    </div>
</main>
{% endblock %}